Add some papers from ICSE 2024 and FSE 2024
jianyu-niu/blockchain_conference_paper pull request #55
Opened 2024-05-17 21:02 UTC by jeffchen006

I added some papers from FSE 2024 and ICSE 2024, please review. Thanks.

2024-05-18 00:52 UTC, gitferry requested changes
Nice addtion! Please address the comments:

2024-05-18 00:52 UTC, gitferry commented on README.md
> +
empty line

2024-05-18 00:52 UTC, gitferry commented on README.md
> +
empty lines

2024-05-18 14:05 UTC, jeffchen006 commented
Empty lines fixed

2024-05-20 08:52 UTC, gitferry approved these changes
Nice additon!

2024-05-20 08:53 UTC, merged